// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzmL4h4nBHEvF4cvpYmzDEmoCS8v-MKFc',
    appId: '1:285043844672:web:d8fe6dfa1c05197fa461a5',
    messagingSenderId: '285043844672',
    projectId: 'flutternotes-b5a50',
    authDomain: 'flutternotes-b5a50.firebaseapp.com',
    storageBucket: 'flutternotes-b5a50.firebasestorage.app',
    measurementId: 'G-DY45TJ2LTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnqKtp2pBYJyes8hOszCjZQvNr8gjKcfQ',
    appId: '1:285043844672:android:e5f60f183097a415a461a5',
    messagingSenderId: '285043844672',
    projectId: 'flutternotes-b5a50',
    storageBucket: 'flutternotes-b5a50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXn41jRkrC8PbtrY9RBlU037Q404Rb3yY',
    appId: '1:285043844672:ios:62a13b10e568be87a461a5',
    messagingSenderId: '285043844672',
    projectId: 'flutternotes-b5a50',
    storageBucket: 'flutternotes-b5a50.firebasestorage.app',
    androidClientId: '285043844672-1r2epef5gqdlf8uc0aueqaqp8bk2edgj.apps.googleusercontent.com',
    iosClientId: '285043844672-rf1smb8ojpi0lrqaa3ds68dbs1q1ps90.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXn41jRkrC8PbtrY9RBlU037Q404Rb3yY',
    appId: '1:285043844672:ios:62a13b10e568be87a461a5',
    messagingSenderId: '285043844672',
    projectId: 'flutternotes-b5a50',
    storageBucket: 'flutternotes-b5a50.firebasestorage.app',
    androidClientId: '285043844672-1r2epef5gqdlf8uc0aueqaqp8bk2edgj.apps.googleusercontent.com',
    iosClientId: '285043844672-rf1smb8ojpi0lrqaa3ds68dbs1q1ps90.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzmL4h4nBHEvF4cvpYmzDEmoCS8v-MKFc',
    appId: '1:285043844672:web:1c16c7c8a1a235fca461a5',
    messagingSenderId: '285043844672',
    projectId: 'flutternotes-b5a50',
    authDomain: 'flutternotes-b5a50.firebaseapp.com',
    storageBucket: 'flutternotes-b5a50.firebasestorage.app',
    measurementId: 'G-11Y6QPTD3P',
  );
}
